
```{r loadData, include=FALSE}
## SCRIPT TO QC AND PROCESS THE KHAMBATA-FORD DATASET
#####
## ANALYST: BRIAN M. BOT
#####

require(synapseClient)
require(rGithubClient)
require(corpcor)
require(lattice)

## SOURCE IN THE DATA EXTRACTION FUNCTIONS
myRepo <- getRepo(repository="Sage-Bionetworks/CRC-RASness",
                  ref="branch", refName="dev")
sourceRepoFile(myRepo, "functions/utilityFunctions.R")



## PULL IN THE DATA AND SUBSET TO COHORT OF INTEREST (TUMOR SAMPLES)
exprSet <- getKhambataFromGEO()
expr <- exprs(exprSet)
clin <- pData(exprSet)
feat <- exprSet@featureData@data

## SVD ON EXPRESSION MATRIX -- ASSESS OVERALL STRUCTURE AND POSSIBLE LATENT STRUCTURE
s <- fs(expr)
```

```{r svdRaw, echo=FALSE}
xyplot(s$d ~ 1:length(s$d),
       xaxt="n",
       xlab="eigen gene",
       ylab="% variance explained")
xyplot(s$v[,2] ~ s$v[,1],
       xlab="1st svd",
       ylab="2nd svd")
```

```{r toGene, include=FALSE}
## LOTS OF VARIATION (DUE TO DIFFERENT TISSUE TYPES?)

## ONE MAJOR OUTLIER
# > colnames(expr)[ which(s$v[,2] < -.7) ]
# [1] "GSM136626"
# Tissue: Adrenal gland; Kidney

## COMBINE TO ONE PROBE PER GENE
idx <- (is.na(feat$"Gene ID")) | (feat$"Gene ID" == "")
expr <- expr[ !idx, ]
feat <- feat[ !idx, ]

exprGene <- combineProbesToGene(expr, feat$"Gene ID")

## MAKE SURE NO LARGE AMOUNTS OF VARIATION HAVE BEEN ADDED BY PROCESS
sGene <- fs(exprGene)
```

```{r svdGene, echo=FALSE}
xyplot(sGene$d ~ 1:length(sGene$d),
       xaxt="n",
       xlab="eigen gene",
       ylab="% variance explained")
xyplot(sGene$v[,2] ~ sGene$v[,1],
       xlab="1st svd",
       ylab="2nd svd")
```

This resulting R object is an `ExpressionSet` containing gene-level expression values as well as clinical information on all samples within the `phenoData` slot of the object.
